CREATE TABLE public.album (
    service_type character varying(100) NOT NULL,
    source_id character varying(100) NOT NULL,
    name character varying(500) NOT NULL,
    artist_name character varying(1000) NOT NULL,
    image_url character varying(300) NOT NULL,
    source_url character varying(2000) NOT NULL,
    region character varying(10) NOT NULL,
    image_thumbnail_url character varying(300) DEFAULT ''::character varying NOT NULL,
    creation_date timestamp with time zone DEFAULT now() NOT NULL,
    upc text DEFAULT ''::text NOT NULL,
    "Id" bigint NOT NULL
);

ALTER TABLE public.album ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."album_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.song (
    service_type character varying(100) NOT NULL,
    source_id character varying(100) NOT NULL,
    name character varying(500) NOT NULL,
    artist_name character varying(1000) NOT NULL,
    album_name character varying(500) NOT NULL,
    album_source_id character varying(100) NOT NULL,
    image_url character varying(300) NOT NULL,
    image_thumbnail_url character varying(300) NOT NULL,
    source_url character varying(2000) NOT NULL,
    region character varying(10) NOT NULL,
    creation_date timestamp with time zone DEFAULT now() NOT NULL,
    isrc text DEFAULT ''::text NOT NULL,
    "Id" bigint NOT NULL
);

ALTER TABLE public.song ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."song_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.album
    ADD CONSTRAINT "PK_Album" PRIMARY KEY ("Id");


ALTER TABLE ONLY public.song
    ADD CONSTRAINT "PK_Song" PRIMARY KEY ("Id");


ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


CREATE UNIQUE INDEX un_album_region_servicetype_sourceid ON public.album USING btree (region, service_type, source_id);
CREATE UNIQUE INDEX un_album_upc_servicetype_region ON public.album USING btree (upc, service_type, region);
CREATE UNIQUE INDEX un_song_isrc_servicetype_region ON public.song USING btree (isrc, service_type, region);
CREATE UNIQUE INDEX un_song_region_servicetype_sourceid ON public.song USING btree (region, service_type, source_id);