version: '3.3'

services:
  mshare.songs.webapi:
    build:
      context: .
      dockerfile: MShare.Songs.WebApi/Dockerfile
    restart: unless-stopped
    depends_on:
      - mshare.dbmigrator
        #condition: service_completed_successfully

  appleproxy:
    container_name: appleproxy
    build:
      context: .
      dockerfile: AppleProxy.WebService/Dockerfile
    restart: unless-stopped

  spotifyproxy:
    build:
      context: .
      dockerfile: SpotifyProxy.WebService/Dockerfile
    restart: unless-stopped

  mshare.database:
    image: postgres:14.5
    restart: always

  mshare.identity.webapi:
    build:
      context: .
      dockerfile: MShare.Identity.WebApi/Dockerfile
    restart: unless-stopped
    depends_on:
      - mshare.dbmigrator
        #condition: service_completed_successfully

  mshare.dbmigrator:
    build:
      context: .
      dockerfile: MShare.DbMigrator/Dockerfile
    depends_on:
      - mshare.database

