version: '3.3'

services:
  mshare.songs.webapi:
    build:
      context: .
      dockerfile: MShare.Songs.WebApi/Dockerfile

  appleproxy:
    container_name: appleproxy
    build:
      context: .
      dockerfile: AppleProxy.WebService/Dockerfile
    restart: unless-stopped
    depends_on:
      - mshare.database

  spotifyproxy:
    build:
      context: .
      dockerfile: SpotifyProxy.WebService/Dockerfile

  mshare.database:
    image: postgres:14.5
    restart: always

