version: '3.3'

services:
  appleproxy:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - APPLE_PROXY_URLS=http://+:5001
    ports:
      - "5001:5001"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  spotifyproxy:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SPOTIFY_PROXY_URLS=http://+:5002
    ports:
      - "5002:5002"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  mshare.songs.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MSHARE_SONGS_URLS=http://+:5003
      - MSHARE_SONGS_ConnectionStrings__DefaultConnection=Host=mshare.database;Port=5432;Database=mshare_songs;Username=root;Password=76G34dZgLmbhVuCYCXz7
    ports:
      - "80:5003"

  mshare.database:
    environment:
      - POSTGRES_PASSWORD=76G34dZgLmbhVuCYCXz7
      - POSTGRES_USER=root
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=mshare_songs
    ports:
      - "5433:5432"
    volumes:
      - ~/Volumes/mshare.database:/var/lib/postgresql/data

