version: '3.8'

services:
  appleproxy:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - APPLE_PROXY_URLS=http://+:5001
    ports:
      - "5001:5001"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  spotifyproxy:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SPOTIFY_PROXY_URLS=http://+:5002
    ports:
      - "5002:5002"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
